pipeline {
    agent any
    
    environment {
        DOCKER_CREDS_ID = 'dockerhub-token' // Matches your exact Jenkins credential ID
        DOCKER_REGISTRY = 'adedolapo05'
    }
    
    stages {
        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Build & Containerize Services') {
            steps {
                script {
                    // Define all 4 of your Java services
                    def services = ['order-service', 'driver-service', 'notification-service', 'tracking-service']
                    
                    // Log into Docker Hub once before running the loop
                    withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDS_ID, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USER --password-stdin"
                    }
                    
                    // Loop through each folder to clean, build, and push
                    for (service in services) {
                        echo "--------------------------------------------------------"
                        echo "Processing: ${service.toUpperCase()}"
                        echo "--------------------------------------------------------"
                        
                        dir("${service}") {
                            // 1. Build the Jar local to its service directory
                            sh "mvn clean test"
                            
                            // 2. Build the Docker image using the corrected Eclipse Temurin base image
                            sh "docker build -t ${env.DOCKER_REGISTRY}/${service}:${env.BUILD_NUMBER} ."
                            
                            // 3. Push to your Docker Hub repository
                            sh "docker push ${env.DOCKER_REGISTRY}/${service}:${env.BUILD_NUMBER}"
                        }
                    }
                }
            }
        }

        stage('Trigger Deployment') {
            steps {
                // Once all 4 images are pushed, trigger your CD job
                build job: 'logistics-cd-pipeline', parameters: [
                    string(name: 'BUILD_NUM', value: "${env.BUILD_NUMBER}")
                ]
            }
        }
    }
}
