pipeline {
    agent any
    
    environment {
        DOCKER_CREDS_ID = 'dockerhub-token' // Your Secret Text credential ID
        DOCKER_REGISTRY = 'adedolapo05'
    }
    
    stages {
        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Build & Containerize Services') {
            steps {
                script {
                    def services = ['order-service', 'driver-service', 'notification-service', 'tracking-service']
                    
                    // Correctly binding 'Secret text' to an environment variable token
                    withCredentials([string(credentialsId: env.DOCKER_CREDS_ID, variable: 'DOCKER_TOKEN')]) {
                        // Pass your username string and use the secret variable token to log in
                        sh "echo \$DOCKER_TOKEN | docker login -u ${env.DOCKER_REGISTRY} --password-stdin"
                    }
                    
                    // Loop through each folder to clean, build, and push
                    for (service in services) {
                        echo "--------------------------------------------------------"
                        echo "Processing: ${service.toUpperCase()}"
                        echo "--------------------------------------------------------"
                        
                        dir("${service}") {
                            // 1. Build the Jar local to its service directory
                            sh "mvn clean test"
                            
                            // 2. Build the Docker image using the corrected Eclipse Temurin base image
                            sh "docker build -t ${env.DOCKER_REGISTRY}/${service}:${env.BUILD_NUMBER} ."
                            
                            // 3. Push to your Docker Hub repository
                            sh "docker push ${env.DOCKER_REGISTRY}/${service}:${env.BUILD_NUMBER}"
                        }
                    }
                }
            }
        }

        stage('Trigger Deployment') {
            steps {
                build job: 'logistics-cd-pipeline', parameters: [
                    string(name: 'BUILD_NUM', value: "${env.BUILD_NUMBER}")
                ]
            }
        }
    }
}
